language: php

services:
  - postgresql
  - mysql

php:
  - 7.2
  - 7.3
  - 7.4

sudo: false

env:
  matrix:
    - DB=mysql DB_DSN='mysql://root@127.0.0.1/cakephp_test'
    - DB=pgsql DB_DSN='postgres://postgres@127.0.0.1/cakephp_test'
    - DB=sqlite DB_DSN='sqlite:///:memory:'

matrix:
  fast_finish: true

before_install:
  - if [[ $DB == 'mysql' ]]; then mysql -u root -e 'CREATE DATABASE cakephp_test;'; fi
  - if [[ $DB == 'pgsql' ]]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi

install:
  - composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit

notifications:
  email: false
